---
env:
  browser: true
  es2021: true
  node: true
extends: 
  - eslint:recommended
  - '@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - security
rules:
  # TypeScript specific rules
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/no-explicit-any': warn
  '@typescript-eslint/prefer-const': error
  '@typescript-eslint/no-inferrable-types': off
  
  # Security rules
  security/detect-non-literal-fs-filename: error
  security/detect-non-literal-regexp: error
  security/detect-unsafe-regex: error
  security/detect-buffer-noassert: error
  security/detect-child-process: error
  security/detect-disable-mustache-escape: error
  security/detect-eval-with-expression: error
  security/detect-no-csrf-before-method-override: error
  security/detect-non-literal-require: error
  security/detect-object-injection: error
  security/detect-possible-timing-attacks: error
  security/detect-pseudoRandomBytes: error
  
  # General JavaScript rules
  prefer-const: error
  no-var: error
  no-console: off
  eqeqeq: error
  curly: error
  
  # Import organization
  sort-imports: 
    - error
    - ignoreCase: true
      ignoreDeclarationSort: true
      
overrides:
  - files: ['**/*.test.ts', '**/*.test.js']
    env:
      jest: true
    rules:
      '@typescript-eslint/no-explicit-any': off
      security/detect-object-injection: off
      
ignorePatterns:
  - node_modules/
  - dist/
  - '*.d.ts'
  - firebase-setup/public/assets/
  - firebase-setup/functions/lib/